# Generated by Django 4.0.6 on 2022-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='experience',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
