# Generated by Django 4.0.6 on 2022-09-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='tickets',
        ),
        migrations.AddField(
            model_name='passenger',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
        ),
    ]
