# Generated by Django 4.0.6 on 2022-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_passenger_tickets_passenger_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='tickets',
        ),
        migrations.AddField(
            model_name='passenger',
            name='tickets',
            field=models.ManyToManyField(to='flights.flight'),
        ),
    ]
